version: '3'
services:
  postgres_db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: minos
      POSTGRES_PASSWORD: minos
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db-data:
