import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@minos/ui/styles/Home.module.css';
import NextLink from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Minoscompare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Minoscompare!</h1>

        <p className={styles.description}>
          Standard <a href="https://next.js.org">Next.js</a> utility links
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <NextLink href="/cpu/search">
            <a className={styles.card}>
              <h2>Search CPUs &rarr;</h2>
              <p>
                Search for CPUs in the database.
              </p>
            </a>
          </NextLink>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
