name: Build
on: push
jobs:
  build:
    if: github.repository == 'minoscompare/minos'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      - name: Generate Prisma Client
        run: yarn gen
      - name: Run Build
        run: yarn build
