name: Build & Deploy
on: push
jobs:
  build:
    if: github.repository == 'minoscompare/minos'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXT_PUBLIC_TYPESENSE_CLIENT_API_KEY: ${{ secrets.NEXT_PUBLIC_TYPESENSE_CLIENT_API_KEY }}
          envkey_NEXT_PUBLIC_TYPESENSE_HOST: ${{ secrets.NEXT_PUBLIC_TYPESENSE_HOST }}
          envkey_NEXT_PUBLIC_TYPESENSE_PORT: ${{ secrets.NEXT_PUBLIC_TYPESENSE_PORT }}
          envkey_NEXT_PUBLIC_TYPESENSE_PROTOCOL: ${{ secrets.NEXT_PUBLIC_TYPESENSE_PROTOCOL }}
          envkey_TYPESENSE_ADMIN_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          fail_on_empty: true
      - name: Install dependencies
        run: yarn
      - name: Generate Prisma Client
        run: yarn gen
      - name: Run Build
        run: yarn build
  deploy:
    if: github.repository == 'minoscompare/minos'
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/minoscompare/minos.git"
          source_branch: ${{ steps.extract_branch.outputs.branch }}
          destination_repo: git@github.com:minoscompare-deployments/minos.git
          destination_branch: ${{ steps.extract_branch.outputs.branch }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
