name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXT_PUBLIC_TYPESENSE_CLIENT_API_KEY: ${{ secrets.NEXT_PUBLIC_TYPESENSE_CLIENT_API_KEY }}
          envkey_NEXT_PUBLIC_TYPESENSE_HOST: ${{ secrets.NEXT_PUBLIC_TYPESENSE_HOST }}
          envkey_NEXT_PUBLIC_TYPESENSE_PORT: ${{ secrets.NEXT_PUBLIC_TYPESENSE_PORT }}
          envkey_NEXT_PUBLIC_TYPESENSE_PROTOCOL: ${{ secrets.NEXT_PUBLIC_TYPESENSE_PROTOCOL }}
          envkey_TYPESENSE_ADMIN_API_KEY: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          fail_on_empty: true
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate Prisma Client
        run: yarn gen
      - name: Build
        run: yarn build
      - name: Deploy to Staging
        id: deploy-vercel-staging
        if: github.event_name == 'push' && github.ref != 'refs/heads/prod'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: .next
      - name: Deploy to Production
        id: deploy-vercel-production
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--prod'
      - name: Preview URL
        run: |
          echo ${{ steps.deploy-vercel-staging.outputs.preview-url }}
